### ISSUE TITLE
Order of operations creates a wrong graph

### ISSUE THREAD

**Issue by gs-gaysii** [nidi3/graphviz-java#26] opened 2017-06-12 16:34 UTC
I am trying to create a graph generically without knowing node dependency upfront. Here's an example that works:

```
        Node h1 = node("h1");
        Node h2 = node("h2");
        Node p = node("p");

        Graph g = graph("example1").directed().with(h1.link(p.link(h2.link(p)).link(h1)));
```

which produces correct graph:
```
digraph "example1" {
        "h1" -> "p"
        "p" -> "h2"
        "p" -> "h1"
        "h2" -> "p"
}
```

However, attempting to produce the same result generically (without knowing upfront what links to what), produces wrong extra line! 

```
        Node h1 = node("h1");
        Node h2 = node("h2");
        Node p = node("p");

        h1 = h1.link(p);
        p = p.link(h2);
        h2 = h2.link(p);

        // This makes a double line from p to h2!!
        p = p.link(h1);

        Graph g = graph("example2").directed().with(h1).with(h2).with(p);
```
Notice extra p to h2!
```
digraph "example2" {
        "h1" -> "p"
        "p" -> "h2"
        "p" -> "h1"
        "p" -> "h2"
        "h2" -> "p"
}
```

However if the order of operations is tweaked, it works(!)

```
        h1 = h1.link(p);
        p = p.link(h1);
        p = p.link(h2);
        h2 = h2.link(p);
```

**Comment by nidi3** [comment] 2017-06-27 19:12
hi @gs-gaysii 
Sorry for the late answer.
I guess the problem is that you reassign the node variables:
```
h1 = h1.link(p);      // h1 is (h1->p)
p = p.link(h2);       // p is (p->h2)
h2 = h2.link(p);      // h2 is (h2->p), p is (p->h2) so h2 is (h2->p->h2)
p = p.link(h1);       // p is ((p->h2)->h1) which is (p->h2,->h1)
```
This does not happen when you change the order of the operations.

**Comment by abhijitdhar** [comment] 2017-07-07 01:31
Is there a way to de-duplicate the double links if they come?

**Comment by gs-gaysii** [comment] 2017-07-10 13:30
Problem is how does one know the order of operations when this is done completely programmatically?

**Comment by abhijitdhar** [comment] 2017-07-12 04:21
Figured it out. So if you sort the dependencies on parent, it works out.

**Closed** 2018-03-19 00:28 UTC
