### ISSUE TITLE
Freezes without exception for w8/Java8

### ISSUE THREAD

**Issue by MerzDaniel** [nidi3/graphviz-java#74] opened 2018-07-29 17:50 UTC
Tried out the simple example graph, but the library freezes on render. 

Debugging into the compiled code showed that the program freezes while trying to load the status
`GraphServerEngine.createSvg(); 
      => Communicator.readStatus()`
`this.readLine()` never returns. 

Is there additional setup needed to make the J2V8 in the background work?

**Comment by nidi3** [comment] 2018-08-03 18:31
This should work without more configurations. What exactly are you doing?
For a working example see https://github.com/nidi3/graphviz-java/blob/6d786895466d4d4ef622e7d05763c9c1bc15693b/graphviz-java/src/test/java/guru/nidi/graphviz/engine/EngineTest.java#L67-L76

But you are right in that the Communicator.read* should have a timeout and not block forever.

**Comment by nidi3** [comment] 2018-08-03 19:37
Added a timeout, but obviously that is not really solving your issue.

**Comment by nidi3** [comment] 2018-08-03 20:11
What is logged?

**Comment by StFS** [comment] 2019-11-18 13:24
I think I may have come across this as well when I tried running tests on my Gradle projects within a docker container.

I got a bunch of these log lines:
```
> Task :test
OpenJDK 64-Bit Server VM warning: You have loaded library /root/libj2v8_linux_x86_64.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
```

And then the whole process just froze (although it looked like the tests finished:

```
> :test > 5 tests completed
<but it just hung there>
```

You can try this out using my gradle plugin project and docker:

```
git clone https://gitlab.com/stfs/gradle-dependency-graph-plugin.git
cd gradle-dependency-graph-plugin
docker run --rm -ti -v $PWD:/code -w /code adoptopenjdk:8-jdk-hotspot ./gradlew check
```

I also tried reproducing this using maven on the graphviz-java project itself. Although I did not experience the same "freeze" behavior, there are a bunch of tests that fail when you run the tests inside a pristine docker container environment it seems. You can try that out with a simple command as well:

```
git clone https://github.com/nidi3/graphviz-java.git
cd graphviz-java
docker run --rm -ti -v $PWD:/code -w /code maven:3-jdk-8  mvn test
```

Of course, this may not have anything at all to do with the freezes but it does seem weird to me that the unit tests fail in a "controlled environment" like that. Maybe this deserves a separate issue (which I can create if asked to).

**Comment by StFS** [comment] 2019-11-18 13:26
well.. I actually may be seeing the "freeze" on the latter example too (when running the `mvn test`) so maybe this bug can be reproduced with that.

**Comment by StFS** [comment] 2019-11-18 13:33
And I should add that if I install the "graphviz" package before running my gradle test suite, the tests work fine. So this seems to be related to the V8 JS engine.

So, this command works:

```
docker run --rm -ti -v $PWD:/code -w /code adoptopenjdk:8-jdk-hotspot bash
<inside docker bash shell>:
apt update
apt install -y graphviz
./gradlew check
```

**Comment by nidi3** [comment] 2020-05-19 13:21
Finally, I have a look at this.
The errors when building graphviz-java on a pristine container is because native dot is required to build it. 
It can be disabled with `docker run --rm -ti -e CI=true -v $PWD:/code -w /code maven:3-jdk-8  mvn test`

**Comment by nidi3** [comment] 2020-05-19 13:26
The stack guard warnings are a J2V8 issue, see https://github.com/nidi3/graphviz-java/issues/76

**Comment by nidi3** [comment] 2020-05-19 14:45
I can reproduce the problem with `gradle-dependency-graph-plugin` but as a gradle dummy, how can I see the log output of the tests?

**Comment by StFS** [comment] 2020-05-19 15:39
@nidi3 you can add `-i` to the gradle command line to increase the log level. Unfortunately, the output doesn't really display much other than what I mentioned above:

```
docker run --rm -ti -v $PWD:/code -w /code adoptopenjdk:8-jdk-hotspot ./gradlew check -i

[...]
> Task :test
Deleting stale output file: /code/build/test-results/test/binary
Deleting stale output file: /code/build/reports/tests/test
Deleting stale output file: /code/build/test-results/test
Deleting stale output file: /code/build/jacoco/test.exec
Downloading https://jcenter.bintray.com/org/jacoco/org.jacoco.agent/0.8.4/org.jacoco.agent-0.8.4.pom to /tmp/gradle_download7173392523526202852bin
Downloading https://jcenter.bintray.com/org/jacoco/org.jacoco.build/0.8.4/org.jacoco.build-0.8.4.pom to /tmp/gradle_download8563787649448945070bin
Downloading https://jcenter.bintray.com/org/jacoco/org.jacoco.agent/0.8.4/org.jacoco.agent-0.8.4.jar to /tmp/gradle_download3557106378267583197bin
Caching disabled for task ':test' because:
  Build cache is disabled
Task ':test' is not up-to-date because:
  No history is available.
Starting process 'Gradle Test Executor 1'. Working directory: /code Command: /opt/java/openjdk/bin/java -Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager -Dorg.gradle.native=false -javaagent:build/tmp/expandedArchives/org.jacoco.agent-0.8.4.jar_982888894296538c98d7324f3ca78d8f/jacocoagent.jar=destfile=build/jacoco/test.exec,append=true,inclnolocationclasses=false,dumponexit=true,output=file,jmx=false -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -ea -cp /root/.gradle/caches/5.6.4/workerMain/gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 1'
Successfully started process 'Gradle Test Executor 1'

Gradle Test Executor 1 started executing tests.

> Task :test

com.gitlab.stfs.gradle.dependencygraph.GradleDependencyGraphPluginTest > can execute dependencyGraph task with Gradle version 4.10.3 STANDARD_OUT
    Downloading https://services.gradle.org/distributions/gradle-4.10.3-bin.zip
    ..........................................................................
OpenJDK 64-Bit Server VM warning: You have loaded library /root/libj2v8_linux_x86_64.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.

com.gitlab.stfs.gradle.dependencygraph.GradleDependencyGraphPluginTest > can execute dependencyGraph task with Gradle version 5.6.2 STANDARD_OUT
    Downloading https://services.gradle.org/distributions/gradle-5.6.2-bin.zip
    .........................................................................................
OpenJDK 64-Bit Server VM warning: You have loaded library /root/libj2v8_linux_x86_64.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.

Gradle Test Executor 1 finished executing tests.
<========-----> 66% EXECUTING [10m 23s]
> IDLE
> IDLE
> IDLE
> :test > 5 tests completed
```

**Comment by nidi3** [comment] 2020-05-19 15:48
Thanks, I tried this and also 
```
test {
    testLogging {
        showStandardStreams = true
    }
}
``` 

but nothing seems to work :(

**Comment by nidi3** [comment] 2020-05-19 15:57
It should also be in `build/reports/tests/test.html` but I don't see it.
https://stackoverflow.com/questions/43289503/where-does-the-output-of-system-out-println-go-in-gradle-test

**Comment by StFS** [comment] 2020-05-19 17:06
Well, I think it's understandable that the html files never get generated because the tests hang, and so the HTML is never created. The tests don't fail, and they don't succeed either, they just never finish.

If I run the tests on my computer directly (not through docker) which has graphviz installed and therefore probably isn't using the J2V8 if I understand this correctly, the tests finish and the HTML is generated.

What output are you looking for specifically? And are you not seeing the same output as I pasted above when you add the `-i` parameter to the docker/gradle command? If not, what are you getting? The tests in the project aren't outputting anything really... are you looking for some log messages from graphviz-java?

If that's the case, there might be an issue because the tests aren't actually loading graphviz-java directly. The tests execute a gradle process that loads the plugin that then uses graphviz-java. The output from that might not be properly routed into the JUnit engine.

Here's the direct link to the unit test if it helps at all:
https://gitlab.com/stfs/gradle-dependency-graph-plugin/-/blob/master/src/test/groovy/com/gitlab/stfs/gradle/dependencygraph/GradleDependencyGraphPluginTest.groovy

**Comment by StFS** [comment] 2020-05-19 17:37
I'm looking at this a bit closer now and if I exec into the same docker container that runs the tests (and is now hanging) and issue a `jps` I see that there is a `GraphvizServer` java process running.

If I kill that process, the tests finish successfully and the HTML gets generated.

So the problem seems to be that the GraphvizServer doesn't detect when it should shut down. I'm not sure where this server is started, or by who for that matter. Is it started in graphviz-java?

**Comment by nidi3** [comment] 2020-05-19 17:44
That sounds definitifely suspicious, I'll check tha. Thanks for the tip.

**Comment by StFS** [comment] 2020-05-19 18:04
I just tried changing my code a bit...

I added `Graphviz.useEngine(new GraphvizJdkEngine());` to the top of the code block where I'm generating the PNG and now my tests pass and if I run it within docker as before the process terminates and everything looks happy.

I'm not 100% sure what I'm doing here though... is it safe for me to force the use of the JDK engine like this? What downsides may that have? In what cases may that fail?

**Comment by nidi3** [comment] 2020-05-19 20:41
Now, everything is clear. The order of engines that are tried is CmdLine, V8, Server, JDK.
- CmdLine does not exist
- V8 does not work because you have to add it explicitly for gradle (https://github.com/nidi3/graphviz-java#maven)
- So, server engine is used

The idea of the server engine is to keep a process with a V8/JDK engine running to avoid initialization cost.
But this use case is probably very rare, so I removed it from the default engines.
So, the problem is solved with `0.16.1` without explicit call to `useEngine`.

The JDK engine is perfectly fine as it supports old Nashorn and new Graal Javascript engines.
The V8 engine is faster than the JDK engines, but as mentioned, you have to put it explicitly on the classpath.

**Comment by StFS** [comment] 2020-05-19 22:05
Awesome! Thank you so much. That solves my problem at least, but I must admit that after diving into this, it may very well be that my problem has nothing to do with the original problem reported in this issue.

**Comment by nidi3** [comment] 2020-05-20 08:36
You are probably right, but I'm closing it anyways.
If there's still a problem, reopen this or create a new issue.

**Closed by nidi3** 2020-05-20 08:36 UTC
Labels: bug
