### ISSUE TITLE
java.io.IOException: Warning: flat edge between adjacent nodes one of which has a record shape - replace records with HTML-like labels

### ISSUE THREAD

**Issue by SebRut** [nidi3/graphviz-java#88] opened 2018-11-13 07:45 UTC
Linking nodes with `shape=Mrecord` using `node.addLink(to(otherNode).with("constraint", false))` leads to the following log message and stops the generation of the graph.

`Caused by: java.io.IOException: Warning: flat edge between adjacent nodes one of which has a record shape - replace records with HTML-like labels`

**Comment by nidi3** [comment] 2018-11-13 13:09
I cannot reproduce the issue, please provide a complete example.

**Comment by nidi3** [comment] 2018-11-15 10:56
Ok, now I can reproduce it.
But the question is what are you trying to achieve? The example is probably too much stripped down to make any sense.
In the end, this is a message from the graphviz implementation, so the java library cannot do much about it.

**Comment by SebRut** [comment] 2018-11-15 11:36
> But the question is what are you trying to achieve?

I tried to create a directed graph where multiple nodes with `record`-shape on one level are connected with invisible edges to preserve a certain order. Linking them without passing `constraint=false` leads to some kind diagonal alignment.

> In the end, this is a message from the graphviz implementation

In my example the Exception thrown makes it clear, that the exception is a result of a message fro mthe graphviz impl, but my original `IOException` lead me to the idea that this exception might be related to `graphviz-java`.

**Comment by nidi3** [comment] 2018-11-15 16:28
So I close it.

**Closed by nidi3** 2018-11-15 16:28 UTC
