### ISSUE TITLE
Rendering Problem

### ISSUE THREAD

**Issue by BaroDevelopment** [nidi3/graphviz-java#118] opened 2019-07-22 15:11 UTC
Hello,

I've copy pasted the example code from the the README.md.
It is working actually but the problem is the size of the generated image.
It looks like this:
![grafik](https://user-images.githubusercontent.com/8499987/61643636-9589e600-aca3-11e9-9323-52efb09ea046.png)

but actually it should look like this:
![grafik](https://user-images.githubusercontent.com/8499987/61643683-a89cb600-aca3-11e9-969a-4004691737c6.png)

I don't know what is wrong. The code is a simple copy paste from the examples and looks like this:

```java
        Graph g = graph("example1").directed()
                .graphAttr().with(RankDir.LEFT_TO_RIGHT)
                .with(
                        node("a").with(Color.RED).link(node("b")),
                        node("b").link(to(node("c")).with(Style.DASHED))
                );
        try {
            Graphviz.fromGraph(g).height(100).render(Format.PNG).toFile(new File("example/ex1.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
```

**Comment by dhu2017** [comment] 2019-07-24 07:19
This bug appears with the latest versions. After rolled back to v0.8.0, it's working properly.

**Comment by nidi3** [comment] 2019-07-26 05:53
I changed something in 0.8.4 regarding the image size.
But I cannot reproduce this issue neither with 0.8.0 nor with 0.8.10. The resulting image has always 100px height.
Maybe it's the graphviz version you have on your machine, can you try adding `Graphviz.useEngine(new GraphvizV8Engine())` at the beginning?

**Comment by nidi3** [comment] 2019-09-20 13:18
I found an issue that could cause your problem. It is fixed in version 0.11.0. Please check it out.

**Comment by jorgemera** [comment] 2019-10-31 18:28
hi,
how can i do to start and configure the Graphviz.useEngine () method?

**Comment by nidi3** [comment] 2019-11-10 12:03
Just call `Graphviz.useEngine(new GraphvizV8Engine())` at the beginning of your program.

**Comment by nidi3** [comment] 2019-11-12 15:58
Additionally in version `0.11.1`, the image sizing is improved and maybe thus the issue is solved?

**Comment by nidi3** [comment] 2020-01-23 21:26
Any news here?

**Comment by nidi3** [comment] 2020-03-08 23:25
Closing this. Feel free to reopen if the problem is still here.

**Closed by nidi3** 2020-03-08 23:25 UTC
