### ISSUE TITLE
NullPointerException when calling toFile

### ISSUE THREAD

**Issue by jacobilsoe** [nidi3/graphviz-java#41] opened 2018-01-16 14:45 UTC
I am using version 0.2.3 and I get a NullPointerException when trying to output to a file. Here's a minimal example to reproduce the problem:

`Graphviz.fromGraph(graph("g")).render(Format.PNG).toFile(new File("./a.png"));`

Stacktrace:

```
Caused by: java.lang.NullPointerException
        at guru.nidi.graphviz.engine.GraphvizV8Engine.release(GraphvizV8Engine.java:38)
        at guru.nidi.graphviz.engine.AbstractGraphvizEngine.initTask(AbstractGraphvizEngine.java:46)
        at guru.nidi.graphviz.engine.AbstractGraphvizEngine.init(AbstractGraphvizEngine.java:34)
        at guru.nidi.graphviz.engine.Graphviz.doUseEngine(Graphviz.java:82)
        at guru.nidi.graphviz.engine.Graphviz.lambda$doUseEngine$15(Graphviz.java:82)
        at guru.nidi.graphviz.engine.AbstractGraphvizEngine.initTask(AbstractGraphvizEngine.java:47)
        at guru.nidi.graphviz.engine.AbstractGraphvizEngine.init(AbstractGraphvizEngine.java:34)
        at guru.nidi.graphviz.engine.Graphviz.doUseEngine(Graphviz.java:82)
        at guru.nidi.graphviz.engine.Graphviz.useEngine(Graphviz.java:74)
        at guru.nidi.graphviz.engine.Graphviz.useEngine(Graphviz.java:55)
        at guru.nidi.graphviz.engine.Graphviz.useDefaultEngines(Graphviz.java:47)
        at guru.nidi.graphviz.engine.Graphviz.getEngine(Graphviz.java:88)
        at guru.nidi.graphviz.engine.Graphviz.execute(Graphviz.java:170)
        at guru.nidi.graphviz.engine.Renderer.toImage(Renderer.java:68)
        at guru.nidi.graphviz.engine.Renderer.toFile(Renderer.java:46)
```
 Am I missing something?

**Comment by nidi3** [comment] 2018-01-16 15:23
There should be an error message logged.
Do you have a logger configured?

**Comment by jacobilsoe** [comment] 2018-01-16 15:45
No, I haven't configured a logger. Will try that. Sometimes the toFile call just hangs and sometimes I get this:
```
Caused by: java.lang.Error: Invalid V8 thread access
        at com.eclipsesource.v8.V8Locker.checkThread(V8Locker.java:56)
        at com.eclipsesource.v8.V8.checkThread(V8.java:676)
        at com.eclipsesource.v8.V8.executeStringScript(V8.java:499)
        at com.eclipsesource.v8.V8.executeStringScript(V8.java:483)
        at guru.nidi.graphviz.engine.GraphvizV8Engine.jsExecute(GraphvizV8Engine.java:53)
        at guru.nidi.graphviz.engine.AbstractJsGraphvizEngine.execute(AbstractJsGraphvizEngine.java:28)
        at guru.nidi.graphviz.engine.Graphviz.execute(Graphviz.java:170)
        at guru.nidi.graphviz.engine.Renderer.toImage(Renderer.java:68)
        at guru.nidi.graphviz.engine.Renderer.toFile(Renderer.java:46)
        at guru.nidi.graphviz.engine.Renderer$toFile.call(Unknown Source)
```
I am running the code from a Gradle build so maybe that's what's causing the instability?

**Comment by jacobilsoe** [comment] 2018-01-16 15:45
And sometimes it works. 😄

**Comment by nidi3** [comment] 2018-01-16 15:52
I guess the problem happens with concurrent calls to Graphviz.
gradle does parallel tests or something similar?

**Comment by jacobilsoe** [comment] 2018-01-16 15:57
Yes, it looks like a multithreading issue.

**Comment by nidi3** [comment] 2018-01-17 23:11
I think I fixed the second case.
Can you try it again with version 0.2.4-SNAPSHOT?
(available at https://oss.sonatype.org/content/repositories/snapshots)

**Comment by jacobilsoe** [comment] 2018-01-18 08:40
Thank you for the quick fix. It is much more stable now. I've been testing it by running it in a loop and usually generation takes a couple of seconds but one time it took 55s and one time it timed out with this error:

`Initializing graphviz engine took too long.`

I run the code from Gradle and I use a Gradle daemon which means that the same Java process is used each time.

**Comment by nidi3** [comment] 2018-01-21 21:45
So the problem occurs only in your load test and not in normal usage?
The current state is stable enough?

**Comment by jacobilsoe** [comment] 2018-01-22 15:22
No, the timeout regularly occurs - also when not load testing.

**Comment by wouterv** [comment] 2018-03-09 13:01
We had problems with the "Caused by: java.lang.Error: Invalid V8 thread access" error as well. We used a single thread executor to generate diagrams as a workaround, so we are looking forward to the 0.2.4 release.

**Comment by nidi3** [comment] 2018-03-18 16:49
It's still not perfect, but 0.2.4 is released now.

**Comment by wouterv** [comment] 2018-03-22 13:13
Thanks, looks like it is working for us. :thumbsup:

**Comment by nidi3** [comment] 2020-05-19 12:49
Is this still a problem?
I'm closing the issue, but feel free to reopen it, and I try to have another look at it.

**Closed by nidi3** 2020-05-19 12:49 UTC
Labels: bug
